// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestProject1;

[TestFixture]
public class HepsiburadaGirisTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void hepsiburadaGiris()
    {
        driver.Navigate().GoToUrl("https://www.hepsiburada.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1152, 924);

        Thread.Sleep(5000);

        IWebElement a= driver.FindElement(By.Id("myAccount"));


        new Actions(driver)
               .MoveToElement(a)
               .Perform();

        driver.FindElement(By.Id("login")).Click();

        Thread.Sleep(5000);

        driver.FindElement(By.Id("txtUserName")).Click();
        driver.FindElement(By.Id("txtUserName")).SendKeys("lmnfnrbhc@gmail.com");
        driver.FindElement(By.Id("btnLogin")).Click();
        {
            var element = driver.FindElement(By.Id("btnLogin"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Thread.Sleep(1000);    

        driver.FindElement(By.Id("txtPassword")).SendKeys("8DWf3#uqfELpV$j");
       
        Thread.Sleep(3000);    

        driver.FindElement(By.Id("btnEmailSelect")).Click();

        Thread.Sleep(3000);
        //hepsiburadadan kaynaklý hata alýyo
        Assert.AreEqual(driver.Url, "https://www.hepsiburada.com/");

    }
}
