// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AfadDepremler', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('AfadDepremler', async function() {
    await driver.get("https://deprem.afad.gov.tr/home-page")
    //// olmuyo

    await driver.sleep(1500);

    await driver.findElement(By.id("25")).click()

    await driver.sleep(50);
    await driver.findElement(By.linkText("Son Depremler Listesi")).click()

    await driver.sleep(500);

    console.log( await driver.findElement(By.css("tbody > .ng-star-inserted:nth-child(1) > .ng-star-inserted:nth-child(1)")).getText())
    await driver.findElement(By.css("tbody > .ng-star-inserted:nth-child(1) > .ng-star-inserted:nth-child(6)"))
    await driver.findElement(By.css("tbody > .ng-star-inserted:nth-child(1) > .ng-star-inserted:nth-child(7)"))
    await driver.findElement(By.css(".k-alt:nth-child(2) > .ng-star-inserted:nth-child(1)"))
    await driver.findElement(By.css(".k-alt:nth-child(2) > .ng-star-inserted:nth-child(6)"))
    await driver.findElement(By.css(".k-alt:nth-child(2) > .ng-star-inserted:nth-child(7)"))

    await driver.sleep(5000);
  })
})
